[CmdletBinding()]
param(
    [ValidateSet('Release', 'RelWithDebInfo', 'Debug')]
    [string]$Configuration = 'Release',
    [switch]$WithDLC
)

$ErrorActionPreference = 'Stop'
$source = $PSScriptRoot
$build = if ($WithDLC) { Join-Path $source 'build-dlc' } else { Join-Path $source 'build-clean' }
$dlcFlag = if ($WithDLC) { "-DENABLE_EXTENDED_HOOKS=ON" } else { "-DENABLE_EXTENDED_HOOKS=OFF" }
$variantTag = if ($WithDLC) { "-DLC" } else { "" }
$subFolder = if ($WithDLC) { "GitHub-DLC" } else { "NexusMods" }

$vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'

if (-not (Test-Path -LiteralPath $vswhere)) {
    throw 'Visual Studio Installer was not found. Install Visual Studio Build Tools with Desktop development with C++.'
}

$visualStudio = & $vswhere -latest -version '[17.0,20.0)' -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
if (-not $visualStudio) {
    $visualStudio = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
}
if (-not $visualStudio) {
    # Preview/Insiders installations can contain a complete C++ workload while
    # not yet being registered with an older vswhere. Probe the known VS 18
    # channel paths before reporting that the compiler is missing.
    $visualStudio = @(
        (Join-Path $env:ProgramFiles 'Microsoft Visual Studio\18\Insiders'),
        (Join-Path $env:ProgramFiles 'Microsoft Visual Studio\18\Preview')
    ) | Where-Object {
        Test-Path -LiteralPath (Join-Path $_ 'VC\Auxiliary\Build\vcvars64.bat')
    } | Select-Object -First 1
}
if (-not $visualStudio) {
    throw 'The Visual Studio C++ x64 compiler is missing. Add the Desktop development with C++ workload.'
}

$vcvars = Join-Path $visualStudio 'VC\Auxiliary\Build\vcvars64.bat'
$ninja = Join-Path $visualStudio 'Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe'
$vsCmake = Join-Path $visualStudio 'Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe'
if (Test-Path -LiteralPath $vsCmake) {
    $env:PATH = "$(Split-Path $vsCmake);$env:PATH"
}

if (-not (Get-Command cmake.exe -ErrorAction SilentlyContinue)) {
    throw 'CMake was not found. Install CMake or add it to PATH.'
}
if (-not (Test-Path -LiteralPath $vcvars)) { throw "Developer environment not found: $vcvars" }
if (-not (Test-Path -LiteralPath $ninja)) { throw "Ninja not found: $ninja" }

# Fresh build timestamp on EVERY build: writing this header forces mod.cpp
# (which prints it at init) to recompile, so the in-game "built ..." string
# always matches the actual binary - never a stale __DATE__/__TIME__.
$stampHeader = Join-Path $source 'src\core\build_timestamp.h'
$stamp = (Get-Date).ToString('MMM d yyyy HH:mm:ss', [Globalization.CultureInfo]::InvariantCulture)
@"
// AUTO-GENERATED by Build_Trinity.ps1 - do not edit. Refreshed every build.
#pragma once
#define TRINITY_BUILD_TIME "$stamp"
"@ | Set-Content -LiteralPath $stampHeader -Encoding ASCII

$configure = '"{0}" >nul && cmake.exe -S "{1}" -B "{2}" -G Ninja -DCMAKE_BUILD_TYPE={3} -DCMAKE_MAKE_PROGRAM="{4}" {5}' -f
    $vcvars, $source, $build, $Configuration, $ninja, $dlcFlag
$compile = '"{0}" >nul && cmake.exe --build "{1}"' -f $vcvars, $build

& cmd.exe /d /s /c $configure
if ($LASTEXITCODE -ne 0) { throw "CMake configuration failed with exit code $LASTEXITCODE." }
& cmd.exe /d /s /c $compile
if ($LASTEXITCODE -ne 0) { throw "Build failed with exit code $LASTEXITCODE." }

$asi = Get-ChildItem -LiteralPath $build -Recurse -Filter '*.asi' |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1
if (-not $asi) { throw 'Build completed, but Trinity.asi was not found.' }

$releaseDir = Join-Path $source 'build\Release'
if (-not (Test-Path -LiteralPath $releaseDir)) {
    New-Item -ItemType Directory -Path $releaseDir -Force | Out-Null
}

$destinationAsi = Join-Path $releaseDir $asi.Name
Copy-Item -Path $asi.FullName -Destination $destinationAsi -Force
Write-Host "Copied to: $destinationAsi"

# Package directory and ZIP creation for release (Nexus / GitHub)
$pkgDir = Join-Path $releaseDir 'package'
if (Test-Path -LiteralPath $pkgDir) {
    try {
        Remove-Item -LiteralPath $pkgDir -Recurse -Force -ErrorAction SilentlyContinue
    } catch {}
}
if (-not (Test-Path -LiteralPath $pkgDir)) {
    New-Item -ItemType Directory -Path $pkgDir -Force | Out-Null
}

Copy-Item -Path $asi.FullName -Destination (Join-Path $pkgDir 'Trinity.asi') -Force

# Example Configuration
$cfgExample = Join-Path $source 'config\Trinity.ini.example'
if (-not (Test-Path -LiteralPath $cfgExample)) { $cfgExample = Join-Path $source 'Trinity.ini.example' }
if (Test-Path -LiteralPath $cfgExample) {
    Copy-Item -Path $cfgExample -Destination (Join-Path $pkgDir 'Trinity.ini.example') -Force
}

if (Test-Path (Join-Path $source 'README.md')) {
    Copy-Item -Path (Join-Path $source 'README.md') -Destination (Join-Path $pkgDir 'README.md') -Force
}

$parentDir = Split-Path $source -Parent

# Extract clean numeric version (e.g. 2.00.01)
$versionHeader = Get-Content (Join-Path $source 'src\core\version.h') -Raw
$numMatch = [regex]::Match($versionHeader, '#define\s+TRINITY_VERSION_NUM\s+"([^"]+)"')
if ($numMatch.Success) {
    $versionStr = $numMatch.Groups[1].Value
} else {
    $majorMatch = [regex]::Match($versionHeader, '#define\s+TRINITY_VERSION_MAJOR\s+(\d+)')
    $minorMatch = [regex]::Match($versionHeader, '#define\s+TRINITY_VERSION_MINOR\s+(\d+)')
    $patchMatch = [regex]::Match($versionHeader, '#define\s+TRINITY_VERSION_PATCH\s+(\d+)')
    if ($majorMatch.Success -and $minorMatch.Success -and $patchMatch.Success) {
        $versionStr = "$($majorMatch.Groups[1].Value).$($minorMatch.Groups[1].Value).$($patchMatch.Groups[1].Value)"
    } else {
        $versionStr = "1.3.3"
    }
}

# Mod Manager Metadata (DMM / Fluffy / Vortex identification)
$modInfoContent = @"
name=Trinity - vTweak
version=$versionStr
description=DirectX 12 Mod Menu for Crimson Desert (Trinity-zhcn)
author=adhksosne (Trinity-zhcn)
category=Utilities
"@
Set-Content -Path (Join-Path $pkgDir 'modinfo.ini') -Value $modInfoContent -Encoding UTF8

$infoJsonContent = @"
{
  "name": "Trinity - vTweak",
  "version": "$versionStr",
  "author": "adhksosne (Trinity-zhcn)",
  "description": "DirectX 12 Mod Menu for Crimson Desert (Trinity-zhcn)",
  "category": "Utilities"
}
"@
Set-Content -Path (Join-Path $pkgDir 'info.json') -Value $infoJsonContent -Encoding UTF8

# Copy ASI Loader (winmm.dll) and checksum file
$winmmPath = Join-Path $source 'loader\winmm.dll'
if (-not (Test-Path -LiteralPath $winmmPath)) { $winmmPath = Join-Path $parentDir 'kebutuhan\Mod_Files\winmm.dll' }
if (-not (Test-Path -LiteralPath $winmmPath)) { $winmmPath = Join-Path $parentDir 'Mod_Files\winmm.dll' }
if (-not (Test-Path -LiteralPath $winmmPath)) { $winmmPath = Join-Path $parentDir 'winmm.dll' }
if (-not (Test-Path -LiteralPath $winmmPath)) { $winmmPath = Join-Path $source 'winmm.dll' }
if (Test-Path -LiteralPath $winmmPath) {
    Copy-Item -Path $winmmPath -Destination (Join-Path $pkgDir 'winmm.dll') -Force
    if (-not (Test-Path (Join-Path $source 'loader\winmm.dll'))) {
        Copy-Item -Path $winmmPath -Destination (Join-Path $source 'loader\winmm.dll') -Force
    }
}

$shaPath = Join-Path $source 'loader\winmm-x64.SHA512'
if (-not (Test-Path -LiteralPath $shaPath)) { $shaPath = Join-Path $parentDir 'kebutuhan\Mod_Files\winmm-x64.SHA512' }
if (-not (Test-Path -LiteralPath $shaPath)) { $shaPath = Join-Path $parentDir 'Mod_Files\winmm-x64.SHA512' }
if (-not (Test-Path -LiteralPath $shaPath)) { $shaPath = Join-Path $parentDir 'winmm-x64.SHA512' }
if (-not (Test-Path -LiteralPath $shaPath)) { $shaPath = Join-Path $source 'winmm-x64.SHA512' }
if (Test-Path -LiteralPath $shaPath) {
    Copy-Item -Path $shaPath -Destination (Join-Path $pkgDir 'winmm-x64.SHA512') -Force
    if (-not (Test-Path (Join-Path $source 'loader\winmm-x64.SHA512'))) {
        Copy-Item -Path $shaPath -Destination (Join-Path $source 'loader\winmm-x64.SHA512') -Force
    }
}

$commonReleaseDir = Join-Path $parentDir "Release\$versionStr"
if (-not (Test-Path -LiteralPath $commonReleaseDir)) {
    New-Item -ItemType Directory -Path $commonReleaseDir -Force | Out-Null
}

$variantReleaseDir = Join-Path $commonReleaseDir $subFolder
if (-not (Test-Path -LiteralPath $variantReleaseDir)) {
    New-Item -ItemType Directory -Path $variantReleaseDir -Force | Out-Null
}

$zipName = "Trinity-v$versionStr-vTweak (2.00.02).zip"
$zipPath = Join-Path $variantReleaseDir $zipName
if (Test-Path -LiteralPath $zipPath) {
    Remove-Item -LiteralPath $zipPath -Force
}

try {
    Start-Sleep -Milliseconds 200
    Compress-Archive -Path "$pkgDir\*" -DestinationPath $zipPath -Force
    Write-Host "Created Release ZIP: $zipPath"

    Copy-Item -Path $zipPath -Destination (Join-Path $commonReleaseDir $zipName) -Force
    Copy-Item -Path $zipPath -Destination (Join-Path $releaseDir $zipName) -Force
} catch {
    Write-Host "Note: Release ZIP creation skipped (file in use): $_"
}

# Copy loose .asi files directly to variant release folder
Copy-Item -Path (Join-Path $pkgDir 'Trinity.asi') -Destination (Join-Path $variantReleaseDir 'Trinity-2.00.02.asi') -Force
Copy-Item -Path (Join-Path $pkgDir 'Trinity.asi') -Destination (Join-Path $variantReleaseDir 'Trinity.asi') -Force

# Setup dedicated Languages folders
$langReleaseDir = Join-Path $commonReleaseDir 'Languages'
if (-not (Test-Path -LiteralPath $langReleaseDir)) {
    New-Item -ItemType Directory -Path $langReleaseDir -Force | Out-Null
}
$variantLangDir = Join-Path $variantReleaseDir 'Languages'
if (-not (Test-Path -LiteralPath $variantLangDir)) {
    New-Item -ItemType Directory -Path $variantLangDir -Force | Out-Null
}

# Auto-deploy to Mod_Files directory
$modFilesDir = Join-Path $parentDir 'Mod_Files'
if (-not (Test-Path -LiteralPath $modFilesDir)) {
    New-Item -ItemType Directory -Path $modFilesDir -Force | Out-Null
}
$modFilesLangDir = Join-Path $modFilesDir 'Languages'
if (-not (Test-Path -LiteralPath $modFilesLangDir)) {
    New-Item -ItemType Directory -Path $modFilesLangDir -Force | Out-Null
}
Copy-Item -Path (Join-Path $pkgDir 'Trinity.asi') -Destination (Join-Path $modFilesDir 'Trinity.asi') -Force

# Auto-deploy to Steam game installation folder
$steamGameDir = "E:\Steam\steamapps\common\Crimson Desert\bin64"
if (-not (Test-Path -LiteralPath $steamGameDir)) {
    $steamGameDir = "C:\Program Files (x86)\Steam\steamapps\common\Crimson Desert\bin64"
}
if (Test-Path -LiteralPath $steamGameDir) {
    try {
        $targetAsi = Join-Path $steamGameDir 'Trinity.asi'
        $bakAsi = Join-Path $steamGameDir 'Trinity.asi.old'
        if (Test-Path -LiteralPath $bakAsi) { [System.IO.File]::Delete($bakAsi) }
        if (Test-Path -LiteralPath $targetAsi) { [System.IO.File]::Move($targetAsi, $bakAsi) }
        Copy-Item -Path (Join-Path $pkgDir 'Trinity.asi') -Destination $targetAsi -Force -ErrorAction Stop
        Write-Host "Auto-deployed to Steam game folder: $steamGameDir"
    } catch {
        Write-Host "Note: Game may be running in bin64, copy skipped (will apply when game restarts): $_"
    }
}

# Auto-deploy to Steam mods folder (ASI only)
$steamModsDir = "E:\Steam\steamapps\common\Crimson Desert\mods"
if (-not (Test-Path -LiteralPath $steamModsDir)) {
    $steamModsDir = "C:\Program Files (x86)\Steam\steamapps\common\Crimson Desert\mods"
}
if (-not (Test-Path -LiteralPath $steamModsDir)) {
    New-Item -ItemType Directory -Path $steamModsDir -Force | Out-Null
}
try {
    Copy-Item -Path (Join-Path $pkgDir 'Trinity.asi') -Destination (Join-Path $steamModsDir 'Trinity.asi') -Force -ErrorAction Stop
    Write-Host "Auto-deployed Trinity.asi to Steam mods folder: $steamModsDir"
} catch {
    Write-Host "Note: Could not copy to mods folder: $_"
}

# Copy and deploy all discovered translation files (*.ini)
$sourceLangDir = Join-Path $source 'languages'
if (-not (Test-Path -LiteralPath $sourceLangDir)) { $sourceLangDir = $source }
Get-ChildItem -Path $sourceLangDir -Filter 'Trinity_*.ini' -File -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item -Path $_.FullName -Destination (Join-Path $langReleaseDir $_.Name) -Force
    Copy-Item -Path $_.FullName -Destination (Join-Path $variantLangDir $_.Name) -Force
    Copy-Item -Path $_.FullName -Destination (Join-Path $modFilesDir $_.Name) -Force
    Copy-Item -Path $_.FullName -Destination (Join-Path $modFilesLangDir $_.Name) -Force
    if (Test-Path -LiteralPath $steamGameDir) {
        Copy-Item -Path $_.FullName -Destination (Join-Path $steamGameDir $_.Name) -Force -ErrorAction SilentlyContinue
        $bin64Lang1 = Join-Path $steamGameDir 'Languages'
        $bin64Lang2 = Join-Path $steamGameDir 'languages'
        New-Item -ItemType Directory -Path $bin64Lang1 -Force | Out-Null
        New-Item -ItemType Directory -Path $bin64Lang2 -Force | Out-Null
        Copy-Item -Path $_.FullName -Destination (Join-Path $bin64Lang1 $_.Name) -Force -ErrorAction SilentlyContinue
        Copy-Item -Path $_.FullName -Destination (Join-Path $bin64Lang2 $_.Name) -Force -ErrorAction SilentlyContinue
    }
    if (Test-Path -LiteralPath $steamModsDir) {
        Copy-Item -Path $_.FullName -Destination (Join-Path $steamModsDir $_.Name) -Force -ErrorAction SilentlyContinue
        $modsLang1 = Join-Path $steamModsDir 'Languages'
        $modsLang2 = Join-Path $steamModsDir 'languages'
        New-Item -ItemType Directory -Path $modsLang1 -Force | Out-Null
        New-Item -ItemType Directory -Path $modsLang2 -Force | Out-Null
        Copy-Item -Path $_.FullName -Destination (Join-Path $modsLang1 $_.Name) -Force -ErrorAction SilentlyContinue
        Copy-Item -Path $_.FullName -Destination (Join-Path $modsLang2 $_.Name) -Force -ErrorAction SilentlyContinue
    }
}
Write-Host "Built: $($asi.FullName)"
